base_images:
  base:
    name: centos
    namespace: openshift
    tag: "7"
  openshift_release_golang-1.17:
    name: release
    namespace: openshift
    tag: golang-1.17
build_root:
  from_repository: true
images:
- from: base
  inputs:
    openshift_release_golang-1.17:
      as:openshift_release_golang-1.17
      - registry.ci.openshift.org/openshift/release:golang-1.17
  to: ci-chat-bot
promotion:
  namespace: ci
  tag: latest
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: master
  org: openshift
  repo: ci-chat-bot
